name: Set random bg

on:
  schedule:
    - cron: '0 */8 * * *' # every hour
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: 'in 1 hour'
        
jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull changes
        run: |
          git pull
      
      - name: Run Python script
        run: |
          python script.py
      
      - name: Commit and push changes
        run: |
          git add .
          git config --global user.email "contacto@pondere.es"
          git config --global user.name "Pondere"
          git commit -m "Automated update"
          git push origin main
